#cloud-config

---
hostname: ${HOSTNAME}

coreos:
  etcd2:
    name: ${HOSTNAME}
    initial-cluster-token: ${TOKEN}
    initial-cluster: ${INITIAL_CLUSTER}
    initial-cluster-state: new
    initial-advertise-peer-urls: http://${ADVERTISE_IP}:2380
    listen-peer-urls: http://${ADVERTISE_IP}:2380
    listen-client-urls: http://${ADVERTISE_IP}:2379,http://127.0.0.1:2379
    advertise-client-urls: http://${ADVERTISE_IP}:2379

  flannel:
    interface: ${ADVERTISE_IP}
    etcd-endpoints: ${ETCD_ENDPOINTS}

  units:
    - name: etcd2.service
      command: start

    - name: flanneld.service
      drop-ins:
      - name: 50-network-config.conf
        content: |
          [Service]
          ExecStartPre=/usr/bin/etcdctl set /coreos.com/network/config '{ "Network": "${POD_NETWORK}" }'

    - name: 10-${NETWORK_INTERFACE}.network
      runtime: true
      content: |
        [Match]
        Name=${NETWORK_INTERFACE}
        [Network]
        Address=${ADVERTISE_IP}/24

    - name: sshd.service
      command: stop

    - name: sshd.socket
      command: start
      content: |
        [Socket]
        ListenStream=22022
        Accept=yes

    - name: docker-tcp.socket
      command: start
      enable: true
      content: |
        [Unit]
        Description=Docker Socket for the API
        Requires=flanneld.service
        After=flanneld.service
        [Socket]
        ListenStream=2375
        Service=docker.service
        BindIPv6Only=both
        [Install]
        WantedBy=sockets.target
users:
- name: core 
  homedir: /home/core
  groups:
  - sudo
  - docker
